---
# tasks file for repos

- name: Ensure fastestmirror Yum plugin is disabled
  lineinfile: dest=/etc/yum/pluginconf.d/fastestmirror.conf
              regexp='^enabled=' line='enabled=0' state=present

- name: Ensure EPEL RPM installed
  yum:  name=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm 
        state=present
