---
- hosts: default
  gather_facts: false

  tasks:
    - name: Ensure libselinux-python installed
      yum:  name=libselinux-python state=present

    - name: Ensure EPEL RPM installed
      yum:  name=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm state=present

    - name: Ensure aliases.sh present
      copy: src=files/aliases.sh dest=/etc/profile.d/aliases.sh
            owner=root group=root mode=0644

    - name: Ensure apache, mysql and php packages installed
      yum:  name={{ item }} state=present
      with_items:
        - httpd
        - mysql-server
        - php
        - php-mysql
        - php-pear

    - name: Create a basic phpinfo() index page
      copy: src=files/index.php dest=/var/www/html/index.php mode=0644 owner=vagrant group=vagrant

    - name: Ensure httpd service is running
      service: name=httpd state=running

    - name: Ensure mysql service is running
      service: name=mysqld state=running

# vim: set ts=2 sw=2:
