---
- hosts: all
  sudo: true

  roles:
    - hosts
    - shell
    - packages
    - repos

- hosts: master
  sudo: true
  roles:
    - ansible
    - vim

- hosts: puppet
  sudo: true
  roles:
    - puppet

- hosts: chef
  sudo: true
  roles:
    - chef

