---
- hosts: all
  sudo: true

  roles:
    - hosts
    - shell
    - packages
    - repos

- hosts: master
  sudo: true
  roles:
    - ansible

- hosts: puppetmaster
  sudo: true
  roles:
    - puppet

- hosts: chef-server
  sudo: true
  roles:
    - chef

