---
- hosts: all
  sudo: true

  roles:
    - { role: hosts, tags: hosts }
    - shell
    - packages
    - repos

- hosts: master
  sudo: true
  roles:
    - ansible
    - vim

- hosts: puppet
  sudo: true
  roles:
    - puppet

- hosts: chef
  sudo: true
  roles:
    - { role: chef, chef_packages: [ chef, chef-server ] }

- hosts: chef-client
  sudo: true
  roles:
    - { role: chef, chef_packages: [ chef ] }
