---
- hosts: all
  sudo: true
  gather_facts: true

  roles:
    - hosts
    - shell
    - packages
    - repos

- hosts: host1
  sudo: true
  roles:
    - ansible

- hosts: host2
  sudo: true
  roles:
    - puppet

- hosts: host3
  sudo: true
  roles:
    - chef
