---
# tasks file for chef

- name: Ensure Chef is installed
  yum: name={{ item }} state=present
  with_items:
    - "{{ chef_packages }}"

- name: Ensure Chef binaries are on the PATH
  template: src=chef.sh.j2 dest=/etc/profile.d/chef.sh
            owner=root group=root mode=0644
