---
# tasks file for hosts
# vim: set syn=ansible:

- name: Ensure hostname set
  hostname: name={{ inventory_hostname }}

- name: Ensure /etc/hosts populated
  template: src=hosts.j2 dest=/etc/hosts owner=root group=root mode=0644
